on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h3>Thanks for opening an issue! We will triage this shortly.<h3>'
          pr-message: '<h3>Thanks for opening an issue! We will review this PR shortly.<h3>'
          footer: '<h5>Come join our discord server (https://discord.gg/HSupF99kpq)! If you have made a contribution, you can claim a special role there!<h5>'
